version: "3.9"

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.6-php8.2-apache
    depends_on: [db]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    ports:
      - "8080:80"
    volumes:
      - wp_core:/var/www/html
      - ./:/var/www/html/wp-content/themes/benwittbrodt

  wpcli:
    image: wordpress:cli-php8.2
    depends_on: [db, wordpress]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    working_dir: /var/www/html
    entrypoint: ["wp"]
    command: ["--path=/var/www/html"]
    volumes:
      - wp_core:/var/www/html
      - ./:/var/www/html/wp-content/themes/benwittbrodt

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on: [db]
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

  # Optional: if you decide to compile Tailwind/JS locally
  node:
    image: node:20-alpine
    working_dir: /theme
    command: sh -lc "npm ci && npm run dev"
    volumes:
      - ./:/theme

volumes:
  db_data:
  wp_core:
